Update metastore.yaml

diff --git a/metastore-manifests/templates/metastore.yaml b/metastore-manifests/templates/metastore.yaml
--- a/metastore-manifests/templates/metastore.yaml
+++ b/metastore-manifests/templates/metastore.yaml
@@ -20,15 +20,23 @@ spec:
             - sh
             - -c
             - |
-               curl -L -o /hive-lib/fb303-0.9.3.jar https://repo1.maven.org/maven2/org/apache/thrift/libfb303/0.9.3/libfb303-0.9.3.jar
-               curl -L -o /hive-lib/libthrift-0.9.3.jar https://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.9.3/libthrift-0.9.3.jar
-               curl -L -o /hive-lib/hive-cli-3.1.3.jar https://repo1.maven.org/maven2/org/apache/hive/hive-cli/3.1.3/hive-cli-3.1.3.jar
-               curl -L -o /hive-lib/hive-exec-3.1.3.jar https://repo1.maven.org/maven2/org/apache/hive/hive-exec/3.1.3/hive-exec-3.1.3.jar
-               curl -L -o /hive-lib/hive-metastore-3.1.3.jar https://repo1.maven.org/maven2/org/apache/hive/hive-metastore/3.1.3/hive-metastore-3.1.3.jar
-               curl -L -o /hive-lib/hive-common-3.1.3.jar https://repo1.maven.org/maven2/org/apache/hive/hive-common/3.1.3/hive-common-3.1.3.jar
+              set -e
+      
+              mkdir -p /hive-lib
+      
+              echo "📦 Downloading required Hive dependencies..."
+      
+              curl -L -o /hive-lib/fb303-0.9.3.jar https://repo1.maven.org/maven2/org/apache/thrift/libfb303/0.9.3/libfb303-0.9.3.jar
+              curl -L -o /hive-lib/libthrift-0.9.3.jar https://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.9.3/libthrift-0.9.3.jar
+              curl -L -o /hive-lib/hive-cli-3.1.3.jar https://repo1.maven.org/maven2/org/apache/hive/hive-cli/3.1.3/hive-cli-3.1.3.jar
+              curl -L -o /hive-lib/hive-exec-3.1.3.jar https://repo1.maven.org/maven2/org/apache/hive/hive-exec/3.1.3/hive-exec-3.1.3.jar
+              curl -L -o /hive-lib/hive-metastore-3.1.3.jar https://repo1.maven.org/maven2/org/apache/hive/hive-metastore/3.1.3/hive-metastore-3.1.3.jar
+              curl -L -o /hive-lib/hive-common-3.1.3.jar https://repo1.maven.org/maven2/org/apache/hive/hive-common/3.1.3/hive-common-3.1.3.jar
+      
+              echo "✅ JARs downloaded."
           volumeMounts:
             - name: shared-jars
-              mountPath: /jars
+              mountPath: /hive-lib
 
       containers:
         - name: metastore
